In [1]:
import pandas as pd
import glob

In [23]:
def binder(path):
    
    path = path
    all_files = glob.glob(path + '*.csv')
    
    li = []

    for filename in all_files:
        df = pd.read_csv(filename, delimiter =';')
        li.append(df)

    df = pd.concat(li, axis = 0)
    df = df.drop_duplicates(keep='last')
    df = df.sort_values(['<DATE>', '<TIME>'], ascending=[True, True])
    
    return(df)

In [26]:
lukoil = binder(path = 'stocks/lukoil/')
lukoil

,<TICKER>,<PER>,<DATE>,<TIME>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<VOL>
123088,LKOH,1,01/02/19,10:01,5265.5,5265.5,5254.0,5254.0,4961
123089,LKOH,1,01/02/19,10:02,5254.0,5255.0,5241.0,5255.0,6430
123090,LKOH,1,01/02/19,10:03,5255.0,5257.5,5250.0,5254.0,991
123091,LKOH,1,01/02/19,10:04,5252.0,5253.0,5251.5,5251.5,198
123092,LKOH,1,01/02/19,10:05,5252.5,5258.0,5252.5,5257.0,377
...,...,...,...,...,...,...,...,...,...
67632,LKOH,1,31/10/19,18:40,5911.0,5917.0,5910.0,5917.0,3257
67633,LKOH,1,31/10/19,18:46,5919.5,5919.5,5919.5,5919.5,155829
67634,LKOH,1,31/10/19,18:48,5919.5,5919.5,5919.5,5919.5,1253
67635,LKOH,1,31/10/19,18:49,5919.5,5919.5,5919.5,5919.5,25
67636,LKOH,1,31/10/19,18:50,5919.5,5919.5,5919.5,5919.5,25

In [27]:
lukoil.to_csv( "stocks/lukoil.csv")